### ISSUE TITLE
Please, form a low-level packages for Base packages

### ISSUE THREAD

**Issue by Anton-Latukha** [emilypi/Base32#13]
(In #12 we moved along with this question) & the more I think, the more I see forming a low-level package more beneficial in the long term. I consider [exposing "Internal" without following PVP convention is a mistake](http://nikita-volkov.github.io/internal-convention-is-a-mistake/).

<details><summary> unwrap: More time consuming path with preservation of a Git history </summary>

</p>

If something: Git history can be carved-out to form what is needed:

Preamble:
0. Clone Git repository into something like `Base-Internal`

When one launches `git filter-branch` (as I in https://github.com/Anton-Latukha/fish-functions/blob/8ebb345c046d493fe966503ea149c5fb63d00ec3/git-pass-filter.fish)
```
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
```
So it itself recommends using https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html.

1. So, to filter a copy of `Base32` history to form a `Base32-Internals` history:
```
git-filter-repo --path-regex 'Internal' --path-regex 'base32' --path-regex 'cabal' --path-regex 'CONTRIBUTING' --path-regex 'default' --path-regex 'LICENSE' --path-regex 'README' --path-regex 'Setup'
# The test/Internal.hs require all other modules
git-filter-repo --invert-paths --path-regex test
```
2. Clean-up the Cabal file.
& it builds:
```
cabal v2-build
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - base32-0.2.0.0 (lib) (configuration changed)
Configuring library for base32-0.2.0.0..
Preprocessing library for base32-0.2.0.0..
Building library for base32-0.2.0.0..
```
3. Change the info in the Cabal file.

In that way from `Base{16,32,64}` you can get 3 Git repos/histories that store only `Internal` information.
If you would want to merge them into 1 repo, then only 1 of them should preserve the general files, and to merge the Git histories:
```
-- go into where to merge
git remote add localPath "<dirToOtherRepo>"
git fetch localPath master
git merge --allow-unrelated-histories localPath/master
```

I'd wanted to help more & done that by myself, done it for Base32 already, but it is awkward to reshape the repositories & and handout results as aka "hear you go, it all works nice and how it should, trust me this is safe".

</details>

Simpler & more effective path - since `Base{16,32,64}` are BSD licensed - source code of internal parts can be combined into 1 package by file merging.

**Comment by emilypi** [comment]
This is possible in the longterm - I have noticed that there are some primitives between all of these libraries that repeat themselves, and it *would* be nice to find some commonalities so that people can more effectively build on the head/inner loop/tail structures I've built to support these 3 packages. I think this would be a useful summer project, but it's not something i have the time to address in the short term unless I have help unfortunately. If you can lend someone who's eager to help structure such a package, I'm happy to write the specification and changes to the naming conventions I'd like to make, as well as co-maintain. Otherwise, I can put a time box on this for probably August. 

In the meantime, I can expose internals, and then do a major version bump when that package is ready.

**Comment by Anton-Latukha** [comment]
Thanks, Emily.

Indeed.

Decided to not bother with it further, therefore just liked the message.

Since you did the https://github.com/emilypi/Base32/issues/12#issuecomment-865290012, I short-circuit this.

It is an implementational detail that would not play a big role in a base encoding libraries, thou Haskell history already teaches us to make multipackages. I work on HNix hoping someday to help with some tooling whoes, there is DHall is already there to ease the Cabal configurations. Tthe Haskell refactoring/module restructuring migration tooling (HLS & company) is not there yet to guide en mass refactors in the code, it should be feasible down the line.

It was distinctly pleasurable chatting with you, you have a nice communication approach.
