### ISSUE TITLE
Support `deepseq` 1.4.5.0

### ISSUE THREAD

**Issue by prikhi** [emilypi/Base32#16]
Can we bump the deepseq upper bound so that v1.4.5 is supported?
https://hackage.haskell.org/package/deepseq-1.4.5.0/changelog

Current bounds are causing failures with stackage nightly builds:
https://github.com/prikhi/stackage/runs/2890239090?check_suite_focus=true

**Comment by emilypi** [comment]
Thanks for raising this @prikhi - revised in r1: https://hackage.haskell.org/package/base32-0.2.1.0/revisions/

**Comment by prikhi** [comment]
Awesome, thanks for the quick turnaround time!
