### ISSUE TITLE
Support deepseq-1.5

### ISSUE THREAD

**Issue by nomeata** [emilypi/Base32#22]
You may already know about this, but just to be able to track this: it seems that base32 needs a release or revision to support deepseq-1.5

**Comment by emilypi** [comment]
Thanks - updating in #23. I'll have a release out today

**Comment by emilypi** [comment]
https://hackage.haskell.org/package/base32-0.4 updated rather than revised so that we could get in @Vlix 's work.

**Comment by emilypi** [comment]
Let me know if you need me to revise 0.3.1 in case you can't upgrade to GHC 9.x
